name: coffee_kst
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  #translate language
  easy_localization:

  #icons and fonts
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  
  #type prams return
  dartz: ^0.10.1

  #state management
  flutter_bloc: ^8.1.1

  #working with entity
  json_annotation:
  equatable: ^2.0.5

  #register bloc
  get_it: ^7.2.0
  
  #api
  dio: ^4.0.6
  
  #internet
  connectivity_plus: ^2.3.6+1
  flutter_spinkit: ^5.1.0

  #database
  hive: ^2.2.3
  hive_flutter:

  #firebase
  firebase_core:
  firebase_auth: ^3.6.0

  #image
  cached_network_image: ^3.2.1
  path_provider: ^2.0.11

  #skeleton
  shimmer: ^2.0.0

  #form_otp
  pinput: ^2.2.12

  #format VND
  intl: 
dev_dependencies:
  flutter_test:
    sdk: flutter

  #working with entity
  build_runner:
  json_serializable:
  hive_generator:
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg_svg/
    - assets/icons/
    - assets/images/settings/
    - assets/translations/
    - assets/images/cart/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
